### ISSUE TITLE
Follow up on "Well-known URL[s]"

### ISSUE THREAD

**Issue by matatk** [w3c/adapt#231]
I think we should look at how to extend and integrate with the "A Well-Known URL for Changing Passwords" spec, as per my [initial message to the list](https://lists.w3.org/Archives/Public/public-adapt/2022Oct/0005.html), and [follow-up message in relation to @rel](https://lists.w3.org/Archives/Public/public-adapt/2022Nov/0004.html). Filing an issue for this as it seems like a good way to track things that the group may want to do as a whole.

**Comment by lwolberg** [comment]
Well Known Destinations is now an active topic at the Adapt TF.

**Comment by lwolberg** [comment]
Now an active topic at the Adapt TF.
